### ISSUE TITLE
Cannot play mp4 online

### ISSUE THREAD

**Issue by NXdriveBeta** [NXdriveBeta/nxdrive-filesys#18]

**Comment by HaoPengNXDrive** [comment]
mp4 file's mime type is wrong in database. Also, cannot play .avi online.

**Comment by KQpiao** [comment]
Cannot play mp3, wmv, wav, mov online

**Comment by NXdriveBeta** [comment]
Should be able to play now. Note that media files uploaded before 7.22 needed to be re-uploaded because their media type in database is wrong.
