### ISSUE TITLE
Cannot open/download item from sharelink

### ISSUE THREAD

**Issue by HaoPengNXDrive** [NXdriveBeta/nxdrive-filesys#28]
Try this one:

https://test.nxdrive.com/share-link/ac1f8731-49dd-4a37-835a-602c5bbc6199/ccd236d6-e2a0-40e3-87fc-2af1612c25e4/brutality.jpg

Cannot view or download.

**Comment by NXdriveBeta** [comment]
Failed to support share link volume and fixed.
